logging:
    level:
        org:
            hibernate: info
spring:
    session:
    
        store-type: none

    devtools:
        livereload:
            enabled: true
        restart:
            enabled: true
        
    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect #org.hibernate.dialect.MySQL5InnoDBDialect  #for deploy         # for test #H2 
        generate-ddl: true
        hibernate:
            ddl-auto: create
        show-sql: true
    mvc:
        static-path-pattern: /static/**
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    resources:
        add-mappings: true
        static-locations: classpath:/static/
    jackson:
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false

##            
## After this, defined in private.yml
##

#spring:
#    datasource:
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        password: [your-password]
#        url: jdbc:mysql://[your-db-url]/jclip?characterEncoding=UTF-8&serverTimezone=UTC
#        username: lee95292
#        
#server:
#    ssl:
#        key-store: keystore.p12
#        key-store-password: [your-password]
#        keyStoreType: PKCS12
#        keyAlias: tomcat
#        port: 8443
#        enabled: true
#
#google :
#  client :
#    clientId : <your-client-id>
#    clientSecret: <your-secret>
#    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
#    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
#    clientAuthenticationScheme: form
#    scope:
#    - email
#    - profile
#  resource:
#    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
